# StringService.srv
string server_address
string server_port_number
string server_destination
string robot_name
string map_id
string ros_domain_id
string maximum_height_for_conversion
string minimum_height_for_conversion
string leaf_size_for_conversion
string grouping_threshold_for_conversion
string voxel_size_for_conversion
string email_address
string slam_type
string ptz_model_name
---
string message
bool success
