# StringService.srv
string map_id
string minimum_height_for_conversion
string maximum_height_for_conversion
string leaf_size_for_conversion
string grouping_threshold_for_conversion
string voxel_size_for_conversion
string robot_interface
string rcs_server_address
string robot_name
string robot_type
string world_id
string workspace
string camera_name
string pointcloud_visualized
string sim
string debug
string ros_domain_id
string lidar_type
string livox_address
string lidar_interface
string slam_type
string min_height_for_move
string cmd_vel_topic
string for_arm_charging
string desired_mode
string ptz_model_name
---
string message
bool success
